### ISSUE TITLE
Typo in crates.io

### ISSUE THREAD

**Issue by Iwark** [mgattozzi/ferris-says#10] opened 2019-01-31 06:15 UTC
Hi,
I'm very new to Rust, but I found a typo in `crates.io` page.

It says:

```
[dependencies]
ferris_says = "0.1"
```

but the correct is `ferris-says`, not `ferris_says`.

Thank you.

**Comment by mgattozzi** [comment] 2019-02-11 16:14
Hi @Iwark and welcome to the community! Thanks for taking the time to open this issue up! This was fixed in https://github.com/mgattozzi/ferris-says/pull/9. I should do a small point release this week to fix it all up!

**Closed as completed by mgattozzi** 2019-02-11 16:14 UTC

**Comment by Iwark** [comment] 2019-02-12 11:00
Oh, I understand!
That's why I couldn't find the typo by searching the master branch...!
It's also interesting that `crates.io` page seems to be generated by README :)

Thanks for your comment anyway!

**Comment by mgattozzi** [comment] 2019-02-12 14:45
@Iwark Yeah it's a neat feature and if you want to enable it in your own crates just point your `Cargo.toml` to it like on [this line](https://github.com/mgattozzi/ferris-says/blob/7799db84f656eabb06263941a2d1e695c607b1c4/Cargo.toml#L9)!

**Comment by serid** [comment] 2019-06-07 21:46
But the issue is still there. On `https://crates.io/crates/ferris-says` it is still `ferris_says = "0.1"` with underscore and not dash as it should be.
![image](https://user-images.githubusercontent.com/30107608/59135198-bcf05200-8986-11e9-9e14-ea70558e46dc.png)

**Comment by dannyvankooten** [comment] 2019-12-13 10:54
Issue is still there because version has not been bumped yet. Let's bump?
